#!/bin/bash
# Install node.js from source, install global packages in node-packages.txt.

VERSION=0.10.5
UNPACKED=node-v$VERSION
ARCHIVE=$UNPACKED.tar.gz

PACKAGES=$NIXD_ETC/node-packages.txt

check() {
    nixd_ls $NIXD_PREFIX/bin/node
    nixd_ls $NIXD_PREFIX/bin/npm
    nixd_newer_than $PACKAGES
}

resources() {
    echo http://nodejs.org/dist/v$VERSION/$ARCHIVE
}

install() {
    if [ ! -e $NIXD_PREFIX/bin/node ]; then
        nixd_echo "Installing node ..."
        tar -xzf $ARCHIVE
        cd $UNPACKED
        ./configure --prefix=$NIXD_PREFIX
        make install
    fi
    nixd_echo "Installing packages listed in $PACKAGES ..."
    cat $PACKAGES | xargs -t -L 1 npm install -g
}

nixd_run "$@"
