#!/bin/bash
# Load poorman bash script, which executes a Procfile with .env.

check() {
    nixd_ls $NIXD_PREFIX/bin/poorman
}

resources() {
    echo https://raw.github.com/rduplain/poorman/master/poorman
}

install() {
    nixd_echo "Verifying download was a script and not a redirect page ..."
    if ( ! grep -q POORMAN_NAME poorman ); then
        nixd_error "Downloaded poorman script does not appear valid."
        return 1
    fi
    nixd_echo "Make script executable ..."
    chmod 775 poorman
    nixd_echo "Install script to $NIXD_PREFIX/bin ..."
    mv -v poorman $NIXD_PREFIX/bin/
}

nixd_run "$@"
