#!/bin/bash

UNPACKED=redis-2.6.13
ARCHIVE=$UNPACKED.tar.gz

check() {
    nixd_ls $NIXD_PREFIX/bin/redis-server
}

resources() {
    echo https://redis.googlecode.com/files/$ARCHIVE
}

install() {
    tar -xzf $ARCHIVE
    cd $UNPACKED
    PREFIX=$NIXD_PREFIX make install
}

nixd_run "$@"
