#!/bin/bash

ARCHIVE=redis-2.6.7.tar.gz
UNPACKED=redis-2.6.7

check() {
    ls $NIXD_PREFIX/bin/redis-server
}

resources() {
    echo http://redis.googlecode.com/files/$ARCHIVE
}

install() {
    tar -xzf $ARCHIVE
    cd $UNPACKED
    PREFIX=$NIXD_PREFIX make install
}

nixd_run "$@"
